# This file configures the static analysis results for your project (errors,
# warnings, and lints).
#
# This enables the 'recommended' set of lints from `package:lints`.
# This set helps identify many issues that may lead to problems when running
# or consuming Dart code, and enforces writing Dart using a single, idiomatic
# style and format.
#
# If you want a smaller set of lints you can change this to specify
# 'package:lints/core.yaml'. These are just the most critical lints
# (the recommended set includes the core lints).
# The core lints are also what is used by pub.dev for scoring packages.

analyzer:
  errors:
    strict_top_level_inference: ignore
include: package:lints/recommended.yaml

linter:
  rules:
    # Fixes '37_class.dart' filename warning
    file_names: false

    # Fixes 'Missing type annotation' on functions and variables
    always_declare_return_types: false
    type_annotate_public_apis: false

    # Fixes 'MyName' and 'Alphaset' naming warnings
    non_constant_identifier_names: false
    # Fixes 'The value of the local variable 'obj' isn't used''

    # Fixes 'Unnecessary new keyword'
    unnecessary_new: false

    # General rule to stop nagging about types
    omit_local_variable_types: false
# Uncomment the following section to specify additional rules.

# analyzer:
#   exclude:
#     - path/to/excluded/files/**

# For more information about the core and recommended set of lints, see
# https://dart.dev/go/core-lints

# For additional information about configuring this file, see
# https://dart.dev/guides/language/analysis-options
